### PR TITLE
Changed Fields to PAN-OS 9.0

### PR DESCRIPTION
**Pull request by Houtek**
I have added all new fields for PAN-OS 9.0

https://docs.paloaltonetworks.com/pan-os/9-0/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions.html

### CODE REVIEW

**Comment by Houtek** [comment]
Ok, made a mess with e-mail addresses, reopening PR.

**Comment by danotorrey** [comment]
Perhaps @ceruleancee, @lingpri, or @waab76 can take a look at this?

See docs reference https://docs.graylog.org/en/3.1/pages/integrations/inputs/palo_alto_networks_input.html

**Comment by waab76** [comment]
Also, some screen shots or other information about how this change has been tested would be valuable.

**Comment by Houtek** [comment]
I'll close this pull request and rework it. 
Haven't thought about all aspects in full depth.
Will provide screenshots with the new PR.

**Pull request closed without merging**
